# Generated by Django 3.0 on 2019-12-09 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authority',
            field=models.CharField(choices=[('Owner', 'Pet Owner'), ('Vet', 'Veterinarian'), ('Comp', 'Company')], default='Owner', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='birthdate',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Public Key'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6),
        ),
        migrations.CreateModel(
            name='LatestTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=150, null=True)),
                ('entry_num', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
