# Generated by Django 2.2.7 on 2019-12-01 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20191130_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='birthdate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
