# Generated by Django 2.2.7 on 2019-12-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20191201_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Public Key'),
        ),
    ]
